In [ ]:
from transformers import T5Config, T5ForConditionalGeneration, T5Tokenizer

model_name = "allenai/t5-small-next-word-generator-qoogle"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

def run_model(input_string, **generator_args):
    input_ids = tokenizer.encode(input_string, return_tensors="pt")
    res = model.generate(input_ids, **generator_args)
    output = tokenizer.batch_decode(res, skip_special_tokens=True)
    print(output)
    return output


In [ ]:
run_model("hello how are you")

['ka']


['ka']

In [ ]:
import google.generativeai as genai
genai.configure(api_key="AIzaSyDmj2BnWaYfITySCVaTApr3RHae85RXlJQ")
model = genai.GenerativeModel("gemini-1.5-flash")

In [ ]:
response = model.generate_content("can you write a python code to hello")
print(response.text)

The simplest Python code to print "Hello" is:

```python
print("Hello")
```



In [ ]:
pip install gtts

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 6.5 MB/s eta 0:00:00
  Attempting uninstall: click
    Found existing installation: click 8.2.1
    Uninstalling click-8.2.1:
      Successfully uninstalled click-8.2.1


In [ ]:
from gtts import gTTS
from IPython.display import Audio
text = "Remember to adjust spices to your preference."
tts = gTTS(text=text)
tts.save("voice.mp3")
Audio("voice.mp3")

In [ ]:
pip install contractions

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.9/113.9 kB 6.0 MB/s eta 0:00:00


In [ ]:
#converting to lowercase
text = "GURRAM KOMALI"
text_lower = text.lower()
print(text_lower)

gurram komali


In [ ]:
#removing punctuations from text
import re

text = "KOMALI?"
text_no_punct = re.sub(r'[^\w\s]', '', text)
print(text_no_punct)


KOMALI


In [ ]:
#removes stopwords  in a text
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

text = "This product is really very good and useful"
words = text.lower().split()
filtered = [word for word in words if word not in stop_words]
print(filtered)


['product', 'really', 'good', 'useful']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
#removes numbers from text
text = "GKomali77"
text_no_numbers = re.sub(r'\d+', '', text)
print(text_no_numbers)


GKomali


In [ ]:
#removing urls
text = "komali https://coolstuff.com/deals"
text_no_url = re.sub(r"http\S+|www\S+|https\S+", "", text)
print(text_no_url)


komali 


In [ ]:
#coverting text to tokens(tokenization)
text = "Gurram Komali is Good Girl"
tokens = text.split()
print(tokens)


['Gurram', 'Komali', 'is', 'Good', 'Girl']


In [ ]:
#Stemming
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

words = ["playing", "played", "plays", "player"]
stemmed = [stemmer.stem(word) for word in words]
print(stemmed)


['play', 'play', 'play', 'player']


In [ ]:
# Lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer = WordNetLemmatizer()

words = ["running", "ran", "runs"]
lemmatized = [lemmatizer.lemmatize(word, pos='v') for word in words]
print(lemmatized)


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


['run', 'run', 'run']


In [ ]:
import re

text = "I love this product 😍🔥💯!"
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map
                           u"\U0001F1E0-\U0001F1FF"  # flags
                           "]+", flags=re.UNICODE)

text_no_emoji = emoji_pattern.sub(r'', text)
print(text_no_emoji)


I love this product !


In [ ]:
#term Frequency-Inverse Document Frequency(TF-IDF)
docs = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love deep learning and AI"
]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)

print("Vocabulary:")
print(vectorizer.vocabulary_)

print("\nTF-IDF Matrix:")
print(X.toarray())


Vocabulary:
{'love': 6, 'machine': 7, 'learning': 5, 'is': 4, 'amazing': 1, 'deep': 3, 'and': 2, 'ai': 0}

TF-IDF Matrix:
[[0.         0.         0.         0.         0.         0.48133417
  0.61980538 0.61980538]
 [0.         0.5844829  0.         0.         0.5844829  0.34520502
  0.         0.44451431]
 [0.50461134 0.         0.50461134 0.50461134 0.         0.29803159
  0.38376993 0.        ]]


In [ ]:
#handling contractions
import contractions

text = "I don't like this"
expanded_text = contractions.fix(text)
print(expanded_text)


I do not like this


In [ ]:
#handling misspellings
from textblob import TextBlob

text = "I reaaaly lovd thish produckt! soo mooch "
corrected_text = str(TextBlob(text).correct())
print(corrected_text)

I really love this product! so much 


In [ ]:
#removing extra whitespaces
text = "This   is   spaced   out"
text = re.sub('\s+', ' ', text).strip()

In [54]:
import pandas as pd
import numpy as np

In [91]:
df=pd.read_csv("/content/product_reviews.csv")
df.head()

ProductID UserID     Category  \
0    P00001  U3292       Beauty   
1    P00002  U9426  Electronics   
2    P00003  U3416         Toys   
3    P00004  U5130         Home   
4    P00005  U4571  Electronics   

                                          ReviewText  Rating  ReviewDate  
0  Front perform state science agent the. Imagine...       3  2023-07-23  
1  Many research upon whatever concern drive husb...       5  2024-12-24  
2  Them increase city star thought. Indicate posi...       2  2025-04-16  
3  Still ahead single man decision. Some world fa...       4  2025-04-13  
4  People rock any look material marriage late. T...       1  2025-04-14

In [92]:
text=df["ReviewText"].astype(str)
y=df["Rating"].astype(int)
y

0      3
1      5
2      2
3      4
4      1
      ..
995    5
996    1
997    2
998    4
999    4
Name: Rating, Length: 1000, dtype: int64

In [93]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y)
y

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [95]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text)
tokenizer.texts_to_sequences(text)

[[666,
  481,
  108,
  299,
  109,
  11,
  110,
  572,
  393,
  394,
  482,
  483,
  484,
  300,
  485,
  395,
  301,
  396,
  746,
  573,
  747,
  302,
  43,
  32,
  486,
  667,
  213,
  214,
  668,
  574,
  215,
  12,
  487],
 [669,
  303,
  111,
  33,
  488,
  66,
  489,
  44,
  575,
  155,
  490,
  12,
  156,
  112,
  6,
  304,
  216,
  485,
  882,
  217,
  218,
  397,
  576,
  157,
  7,
  219,
  67,
  305,
  828,
  113,
  747,
  306],
 [398, 158, 399, 400, 114, 401, 883, 220],
 [748,
  115,
  20,
  829,
  221,
  491,
  884,
  828,
  402,
  222,
  21,
  403,
  68,
  159,
  670,
  749,
  160,
  161,
  223,
  404,
  162],
 [405,
  163,
  13,
  224,
  830,
  406,
  492,
  407,
  671,
  577,
  164,
  750,
  672,
  116,
  493,
  225],
 [304,
  578,
  831,
  226,
  967,
  408,
  115,
  165,
  115,
  117,
  579,
  227,
  832,
  307,
  308,
  924,
  673,
  228,
  833,
  674,
  494,
  22,
  495,
  309,
  69,
  961,
  580,
  496,
  32,
  310,
  581,
  70,
  311,
  582,
  409,
  675,
  305,
 

In [96]:
seq=pad_sequences(tokenizer.texts_to_sequences(text))
seq
#seq=pad_sequences(seq,padding="post")
#seq

array([[  0,   0,   0, ..., 215,  12, 487],
       [  0,   0,   0, ..., 113, 747, 306],
       [  0,   0,   0, ..., 401, 883, 220],
       ...,
       [  0,   0,   0, ...,  52, 269, 639],
       [  0,   0,   0, ..., 370,  93,  60],
       [  0,   0,   0, ...,  70, 115, 579]], dtype=int32)

In [113]:
from sklearn.model_selection import train_test_split
sequences = tokenizer.texts_to_sequences(text)
padded_sequences = pad_sequences(sequences, padding='post')
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, y, test_size=0.2, random_state=42)

In [114]:
seq

array([[  0,   0,   0, ..., 215,  12, 487],
       [  0,   0,   0, ..., 113, 747, 306],
       [  0,   0,   0, ..., 401, 883, 220],
       ...,
       [  0,   0,   0, ...,  52, 269, 639],
       [  0,   0,   0, ..., 370,  93,  60],
       [  0,   0,   0, ...,  70, 115, 579]], dtype=int32)

In [115]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN

In [116]:
dd=len(tokenizer.word_index)+1

In [117]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN, Dense

model=Sequential([
    Embedding(input_dim=dd,output_dim=32),
    SimpleRNN(32),
    Dense(6,activation="softmax")
])

In [118]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [119]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10)

Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.1979 - loss: 1.7662 - val_accuracy: 0.2150 - val_loss: 1.6764
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.2674 - loss: 1.6373 - val_accuracy: 0.2000 - val_loss: 1.6579
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.3380 - loss: 1.5535 - val_accuracy: 0.2500 - val_loss: 1.6890
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5689 - loss: 1.3067 - val_accuracy: 0.2200 - val_loss: 1.7504
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7503 - loss: 0.9904 - val_accuracy: 0.2300 - val_loss: 1.8971
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8872 - loss: 0.7303 - val_accuracy: 0.2150 - val_loss: 2.0434
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9544 - loss: 0.4851 - val_accuracy: 0.2300 - val_loss: 2.1316
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9854 - loss: 0.3059 - val_accuracy: 0.2050 - v

In [121]:
samples = ["The product is worst"]
sample_seq = tokenizer.texts_to_sequences(samples)
sample_pad = pad_sequences(sample_seq)
preds = model.predict(sample_pad)
print(samples)
print(np.argmax(preds)+1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
['The product is worst']
6
